package com.fkzhang.wechatforwarder;

public class f
{
  public String A;
  public String B;
  public String C;
  public String D;
  public String E;
  public String F;
  public String G;
  public String H;
  public String I;
  public String J;
  public String K;
  public String L;
  public String M;
  public String N;
  public String O;
  public String P;
  public String Q;
  public String R;
  public String S;
  public String T;
  public String U;
  public String V;
  public String W;
  public String X;
  public String Y;
  public String Z;
  public String a;/** Modify By Gele **///包名的前部分?com.tencent?
  public String aA;
  public String aB;
  public String aC;
  public String aD;
  public String aE;
  public String aF;
  public String aG;
  public String aH;
  public String aI;
  public String aJ;
  public String aK;
  public String aL;
  public String aM;
  public String aN;
  public String aO;
  public String aP;
  public String aQ;
  public String aR;
  public String aS;
  public String aT;
  public String aU;
  public String aV;
  public String aW;
  public String aX;
  public String aY;
  public String aZ;
  public String aa;
  public String ab;
  public String ac;
  public String ad;
  public String ae;
  public String af;
  public String ag;
  public String ah;
  public String ai;
  public String aj;
  public String ak;
  public String al;
  public String am;
  public String an;
  public String ao;
  public String ap;
  public String aq;
  public String ar;
  public String as;
  public String at;
  public String au;
  public String av;
  public String aw;
  public String ax;
  public String ay;
  public String az;
  public String b;/** Modify By Gele **///包名
  public String bA;
  public String bB;
  public String bC;
  public String bD;
  public String bE;
  public String bF;
  public String bG;
  public String bH;
  public String bI;
  public String bJ;
  public String bK;
  public String bL;
  public String bM;
  public String bN;
  public String bO;
  public String bP;
  public String bQ;
  public String bR;
  public String bS;
  public String bT;
  public String bU;
  public String bV;
  public String bW;
  public String bX;
  public String ba;
  public String bb;
  public String bc;
  public String bd;
  public String be;
  public String bf;
  public String bg;
  public String bh;
  public String bi;
  public String bj;
  public int bk;
  public String bl;
  public String bm;
  public String bn;
  public String bo;
  public String bp;
  public String bq;
  public String br;
  public String bs;
  public String bt;
  public String bu;
  public String bv;
  public String bw;
  public String bx;
  public String by;
  public String bz;
  public String c;
  public String d;
  public String e;
  public String f;
  public String g;
  public String h;
  public String i;
  public String j;
  public String k;
  public String l;
  public String m;
  public String n;
  public String o;
  public String p;
  public String q;
  public String r;
  public String s;
  public String t;
  public String u;
  public String v;
  public String w;
  public String x;
  public String y;
  public String z;
  
  public f(String paramString1, String paramString2)/** Modify By Gele **///包名,版本号
  {
    this.b = paramString1;
    this.a = paramString1.substring(0, paramString1.lastIndexOf("."));
    n();/** Modify By Gele **///初始化关键类名?分析微信结构
    if (paramString2.contains("6.3.15")) {
      m();
    }
    do
    {

      if (paramString2.contains("6.3.13.104"))
      {
        l();
        return;
      }
      if (paramString2.contains("6.3.13"))
      {
        k();
        return;
      }
      if (paramString2.contains("6.3.11"))
      {
        j();
        return;
      }
      if (paramString2.contains("6.3.9"))
      {
        i();
        return;
      }
      if (paramString2.contains("6.3.8"))
      {
        h();
        return;
      }
      if (paramString2.contains("6.3.7"))
      {
        g();
        return;
      }
      if (paramString2.contains("6.3.5.50"))
      {
        f();
        return;
      }
      if (paramString2.contains("6.3.5"))
      {
        e();
        return;
      }
      if (paramString2.contains("6.3.0"))
      {
        d();
        return;
      }
      if (paramString2.contains("6.2.5"))
      {
        c();
        return;
      }
      if (paramString2.contains("6.2.4"))
      {
        b();
        return;
      }
    } while (!paramString2.contains("6.0.0"));
    a();
    return;/** Modyfy By Gele **/
  }
  
  private void a()
  {
    this.m += ".z.ar";
    this.k = "zZ";
    this.aw = "g";
    this.n += ".al.u";
    this.i = "jk";
    this.l = "g";
    this.p = "jj";
    this.o += ".a.f";
    this.j = "ao";
    this.e = "gnN";
    this.f = "jWT";
    this.B += ".hr";
    this.q = (this.u + "ui.bb");
    this.u += "a.e";
    this.r = "je";
    this.s = "gWs";
    this.v = "gWb";
    this.w = "apd";
    this.y = "X";
    this.A = "n";
    this.z = "apc";
    this.x = "ape";
    this.C = "m";
    this.D += "adq";
    this.E = "iZr";
    this.G = "hM";
    this.H = "jE";
    this.I = "g";
    this.J = "sT";
    this.K = "d";
    this.L = "";
    this.M = "";
    this.N = "";
    this.O = "";
    this.P = "";
    this.ao = "";
    this.Q = "aAl";
    this.R = "uK";
    this.S = "k";
    this.T = "aHW";
    this.U = "vo";
    this.V = "axC";
    this.W = "ad";
    this.X = "hbh";
    this.Y = "jMx";
    this.Z = "jhw";
    this.aa = "iXW";
    this.ab = "ayV";
    this.ac = "bp";
    this.ad = "c";
    this.ae = "i";
    this.af += "ai";
    this.ag += "k";
    this.ai += "bh";
    this.ah += "h.f";
    this.aj += "h";
    this.ak += "d.ad";
    this.al += "d.am";
    this.am += "d.ai";
    this.an += "b.k";
    this.bs = "";
    this.bB = "";
    this.bT = (this.b + ".plugin.emoji.c");
    this.bU = "n";
    this.bV = "sS";
    this.bW = "rd";
  }
  
  private void b()
  {
    this.m += ".y.n";
    this.k = "Aa";
    this.aw = "hf";
    this.n += ".ai.n";
    this.i = "iO";
    this.l = "h";
    this.p = "iN";
    this.o += ".a.f";
    this.j = "aA";
    this.e = "eUM";
    this.f = "jnK";
    this.B += ".a";
    this.q += "1";
    this.u += "a.b.b";
    this.r = "lQ";
    this.s = "fES";
    this.v = "fEG";
    this.w = "amL";
    this.y = "x";
    this.A = "j";
    this.z = "amK";
    this.x = "amM";
    this.t = "amW";
    this.C = "ah";
    this.D += "anc";
    this.E = "iln";
    this.G = "hd";
    this.H = "jf";
    this.I = "h";
    this.J = "tw";
    this.K = "d";
    this.L += "cn.5.1";
    this.M += "c.c";
    this.N = "jrG";
    this.O = "jrD";
    this.P = "e";
    this.ao += "cn";
    this.Q = "apX";
    this.R = "rZ";
    this.S = "k";
    this.T = "fHH";
    this.U = "sz";
    this.V = "axQ";
    this.W = "ac";
    this.X = "fVE";
    this.Y = "ilq";
    this.Z = "hLk";
    this.aa = "hCx";
    this.ab = "aoM";
    this.ac = "aX";
    this.ad = "rv";
    this.ae = "rx";
    this.af += "q";
    this.ag += "f";
    this.ai += "ag";
    this.ah += "f.f";
    this.aj += "h";
    this.ak += "c.ad";
    this.al += "c.al";
    this.am += "c.ah";
    this.an += "c.g";
    this.ap = "af";
    this.aq = "aoZ";
    this.as = "sy";
    this.ar = "fLL";
    this.at = "l";
    this.au = "fHy";
    this.av = "sz";
    this.ax = "hBd";
    this.ay = "auM";
    this.az = "ias";
    this.aA = "fSf";
    this.aC += "m";
    this.aD = "Dj";
    this.aE = (this.b + ".ui.tools.ImageGalleryUI");
    this.aF = (this.aE + ".12");
    this.aG = (this.aE + ".2");
    this.aH = "d";
    this.aI = "pr";
    this.aJ = "jOo";
    this.aK = "jKo";
    this.aM += ".2";
    this.aN += ".4";
    this.aO = "d";
    this.aP = "fSy";
    this.aQ = "apR";
    this.aR += "a.k";
    this.aS += ".a.a";
    this.aT = "juP";
    this.aU = "enr";
    this.aV = "f";
    this.aX = "dnW";
    this.aY = "dpH";
    this.aZ = "gs";
    this.ba = "RH";
    this.bb = "bc";
    this.bc = "k";
    this.bd = "hOO";
    this.be = "d";
    this.bf = "c";
    this.bg = "auI";
    this.bh = "hOA";
    this.bi += "f";
    this.bj += "b.t";
    this.bk = 1;
    this.bm = "av";
    this.bn = "tv";
    this.bo = "rp";
    this.bq = "fJ";
    this.bs += "aq";
    this.bt = "ul";
    this.bv = (this.b + ".ab.f");
    this.bw += "f";
    this.bx += "f.d";
    this.by = "a";
    this.bB = (this.bz + ".4.1");
    this.bC = "af";
    this.bD = "aib";
    this.bE = "eYP";
    this.bF = "eYO";
    this.bG = (this.bA + ".11.1");
    this.bH = (this.bA + ".11.2");
    this.bI += "k";
    this.bJ += "a.i";
    this.bK = "a";
    this.bL = "a";
    this.bM = "d";
    this.bN = "c";
    this.bS = "f";
    this.bO = "eYH";
    this.bP = "eYE";
    this.bQ = "aDU";
    this.bR = "axw";
    this.bT = (this.b + ".plugin.emoji.e");
    this.bU = "n";
    this.bV = "tv";
    this.bW = "rH";
  }
  
  private void c()
  {
    this.m += ".z.n";
    this.k = "Ao";
    this.aw = "hs";
    this.n += ".aj.n";
    this.i = "ja";
    this.l = "h";
    this.p = "iZ";
    this.o += ".a.f";
    this.j = "aA";
    this.e = "fbn";
    this.f = "jAS";
    this.B += ".a";
    this.q += "1";
    this.u += "a.b.b";
    this.r = "lP";
    this.s = "fLL";
    this.v = "fLz";
    this.w = "aob";
    this.y = "z";
    this.A = "j";
    this.z = "aoa";
    this.x = "aoc";
    this.t = "aom";
    this.C = "ag";
    this.D += "aok";
    this.E = "ixy";
    this.G = "hq";
    this.H = "js";
    this.I = "i";
    this.J = "tJ";
    this.K = "d";
    this.L += "cn.5.1";
    this.M += "c.c";
    this.N = "jEP";
    this.O = "jEM";
    this.P = "e";
    this.ao += "cn";
    this.Q = "arq";
    this.R = "sA";
    this.S = "j";
    this.T = "aGx";
    this.U = "td";
    this.V = "ayn";
    this.W = "ad";
    this.X = "gda";
    this.Y = "ixB";
    this.Z = "hWp";
    this.aa = "hNm";
    this.ab = "aqa";
    this.ac = "bc";
    this.ad = "rW";
    this.ae = "rY";
    this.af += "q";
    this.ag += "f";
    this.ai += "ah";
    this.ah += "g.f";
    this.aj += "h";
    this.ak += "d.ac";
    this.al += "d.ak";
    this.am += "d.ag";
    this.an += "d.g";
    this.ap = "ag";
    this.aq = "aqn";
    this.as = "tc";
    this.ar = "fSL";
    this.at = "m";
    this.au = "fOK";
    this.av = "td";
    this.ax = "hLG";
    this.ay = "avb";
    this.az = "imr";
    this.aA = "fZz";
    this.aC += "m";
    this.aD = "DJ";
    this.aE = (this.b + ".ui.tools.ImageGalleryUI");
    this.aF = (this.aE + ".12");
    this.aG = (this.aE + ".2");
    this.aH = "d";
    this.aI = "pF";
    this.aJ = "kbI";
    this.aK = "jXJ";
    this.aM += ".2";
    this.aN += ".4";
    this.aO = "d";
    this.aP = "fZS";
    this.aQ = "aqW";
    this.aR += "a.k";
    this.aS += ".a.a";
    this.aT = "jHX";
    this.aU = "etD";
    this.aV = "f";
    this.aX = "drI";
    this.aY = "dtt";
    this.aZ = "gx";
    this.ba = "Sj";
    this.bb = "bf";
    this.bc = "k";
    this.bd = "hZT";
    this.be = "d";
    this.bf = "c";
    this.bg = "auX";
    this.bh = "hZF";
    this.bi += "f";
    this.bj += "b.t";
    this.bk = 1;
    this.bm = "av";
    this.bn = "tI";
    this.bo = "rB";
    this.bq = "fT";
    this.bs += "ar";
    this.bt = "uy";
    this.bv = (this.b + ".ac.g");
    this.bw += "f";
    this.bx += "f.d";
    this.by = "a";
    this.bB = (this.bz + ".4.1");
    this.bC = "ag";
    this.bD = "aje";
    this.bE = "ffr";
    this.bF = "ffq";
    this.bG = (this.bA + ".11.1");
    this.bH = (this.bA + ".11.2");
    this.bI += "k";
    this.bJ += "a.i";
    this.bK = "a";
    this.bL = "a";
    this.bM = "d";
    this.bN = "c";
    this.bS = "f";
    this.bO = "ffj";
    this.bP = "ffg";
    this.bQ = "aEE";
    this.bR = "axT";
    this.bT = (this.b + ".plugin.emoji.f");
    this.bU = "o";
    this.bV = "tl";
    this.bW = "rT";
  }
  
  private void d()
  {
    this.m += ".z.n";
    this.k = "Ar";
    this.aw = "hv";
    this.n += ".ak.n";
    this.i = "jg";
    this.l = "i";
    this.p = "jf";
    this.o += ".a.f";
    this.j = "aD";
    this.e = "fih";
    this.f = "jMw";
    this.B += ".a";
    this.q += "1";
    this.u += "a.b.b";
    this.r = "lV";
    this.s = "fTn";
    this.v = "fTb";
    this.w = "aqa";
    this.y = "z";
    this.A = "j";
    this.z = "apZ";
    this.x = "aqb";
    this.t = "aql";
    this.C = "aj";
    this.D += "apb";
    this.E = "iIM";
    this.G = "ht";
    this.H = "jy";
    this.I = "i";
    this.J = "tM";
    this.K = "d";
    this.L += "cn.5.1";
    this.M += "c.c";
    this.N = "jQs";
    this.O = "jQp";
    this.P = "e";
    this.ao += "cn";
    this.Q = "atq";
    this.R = "sN";
    this.S = "j";
    this.T = "aFJ";
    this.U = "tr";
    this.V = "axb";
    this.W = "ad";
    this.X = "glF";
    this.Y = "iIP";
    this.Z = "igV";
    this.aa = "hXN";
    this.ab = "arZ";
    this.ac = "be";
    this.ad = "sj";
    this.ae = "sl";
    this.af += "q";
    this.ag += "f";
    this.ai += "ah";
    this.ah += "h.f";
    this.aj += "h";
    this.ak += "d.ad";
    this.al += "d.am";
    this.am += "d.ai";
    this.an += "d.g";
    this.ap = "ag";
    this.aq = "asm";
    this.as = "tq";
    this.ar = "gal";
    this.at = "m";
    this.au = "fWl";
    this.av = "tr";
    this.ax = "hWh";
    this.ay = "atL";
    this.az = "ixu";
    this.aA = "gie";
    this.aC += "m";
    this.aD = "DV";
    this.aF += ".12";
    this.aG += ".2";
    this.aH = "d";
    this.aI = "qf";
    this.aJ = "jZz";
    this.aK = "jXj";
    this.aM += ".2";
    this.aN += ".4";
    this.aO = "d";
    this.aP = "gix";
    this.aQ = "asW";
    this.aR += "a.k";
    this.aS += ".a.a";
    this.aT = "jTE";
    this.aU = "exx";
    this.aV = "f";
    this.aX = "duU";
    this.aY = "dwE";
    this.aZ = "gT";
    this.ba = "SY";
    this.bb = "be";
    this.bc = "k";
    this.bd = "ikM";
    this.be = "d";
    this.bf = "c";
    this.bg = "atH";
    this.bh = "iky";
    this.bi += "h";
    this.bj += "b.u";
    this.bm = "ax";
    this.bn = "tL";
    this.bo = "rE";
    this.bq = "gl";
    this.bs += "ar";
    this.bt = "uB";
    this.bv = (this.b + ".ac.g");
    this.bw += "f";
    this.bx += "f.d";
    this.by = "a";
    this.bB = (this.bz + ".4.1");
    this.bC = "am";
    this.bD = "ald";
    this.bE = "fmC";
    this.bF = "fmB";
    this.bG = (this.bA + ".11.1");
    this.bH = (this.bA + ".11.2");
    this.bI += "k";
    this.bJ += "a.m";
    this.bK = "a";
    this.bL = "a";
    this.bM = "d";
    this.bN = "c";
    this.bS = "f";
    this.bO = "fmu";
    this.bP = "fmr";
    this.bQ = "axF";
    this.bR = "awH";
    this.bT = (this.b + ".plugin.emoji.d");
    this.bU = "p";
    this.bV = "tL";
    this.bW = "rW";
  }
  
  private void e()
  {
    this.m += ".z.n";
    this.k = "Aw";
    this.aw = "hv";
    this.n += ".ak.n";
    this.i = "jg";
    this.l = "i";
    this.p = "jf";
    this.o += ".a.f";
    this.j = "aC";
    this.e = "fil";
    this.f = "jMz";
    this.B += ".a";
    this.q += "1";
    this.u += "a.b.b";
    this.r = "lV";
    this.s = "fTr";
    this.v = "fTf";
    this.w = "aqj";
    this.y = "z";
    this.A = "j";
    this.z = "aqi";
    this.x = "aqk";
    this.t = "aqu";
    this.C = "ak";
    this.D += "apb";
    this.E = "iIO";
    this.G = "ht";
    this.H = "jy";
    this.I = "i";
    this.J = "tP";
    this.K = "d";
    this.L += "cn.5.1";
    this.M += "c.c";
    this.N = "jQv";
    this.O = "jQs";
    this.P = "e";
    this.ao += "cn";
    this.Q = "atz";
    this.R = "sO";
    this.S = "j";
    this.T = "aFF";
    this.U = "ts";
    this.V = "awX";
    this.W = "ad";
    this.X = "glJ";
    this.Y = "iIR";
    this.Z = "igX";
    this.aa = "hXP";
    this.ab = "asi";
    this.ac = "be";
    this.ad = "sk";
    this.ae = "sm";
    this.af += "q";
    this.ag += "f";
    this.ai += "ai";
    this.ah += "h.f";
    this.aj += "h";
    this.ak += "d.ad";
    this.al += "d.am";
    this.am += "d.ai";
    this.an += "d.g";
    this.ap = "ag";
    this.aq = "asv";
    this.as = "tr";
    this.ar = "gap";
    this.at = "m";
    this.au = "fWp";
    this.av = "ts";
    this.ax = "hWj";
    this.ay = "atH";
    this.az = "ixw";
    this.aA = "gii";
    this.aC += "m";
    this.aD = "Ea";
    this.aF += ".12";
    this.aG += ".2";
    this.aH = "d";
    this.aI = "qh";
    this.aJ = "jZD";
    this.aK = "jXn";
    this.aM += ".2";
    this.aN += ".4";
    this.aO = "d";
    this.aP = "giB";
    this.aQ = "atf";
    this.aR += "a.k";
    this.aS += ".a.a";
    this.aT = "jTH";
    this.aU = "exw";
    this.aV = "f";
    this.aX = "duS";
    this.aY = "dwC";
    this.aZ = "gT";
    this.ba = "Te";
    this.bb = "bd";
    this.bc = "k";
    this.bd = "ikO";
    this.be = "d";
    this.bf = "c";
    this.bg = "atD";
    this.bh = "ikA";
    this.bi += "h";
    this.bj += "b.u";
    this.bm = "ax";
    this.bn = "tO";
    this.bo = "rH";
    this.bq = "gn";
    this.bs += "at";
    this.bt = "uq";
    this.bv = (this.b + ".ac.g");
    this.bw += "f";
    this.bx += "f.d";
    this.by = "a";
    this.bB = (this.bz + ".4.1");
    this.bC = "am";
    this.bD = "alm";
    this.bE = "fmG";
    this.bF = "fmF";
    this.bG = (this.bA + ".11.1");
    this.bH = (this.bA + ".11.2");
    this.bI += "k";
    this.bJ += "a.l";
    this.bK = "a";
    this.bL = "a";
    this.bM = "d";
    this.bN = "c";
    this.bS = "f";
    this.bO = "fmy";
    this.bP = "fmv";
    this.bQ = "axB";
    this.bR = "awD";
    this.bT = (this.b + ".plugin.emoji.d");
    this.bU = "p";
    this.bV = "tO";
    this.bW = "rZ";
  }
  
  private void f()
  {
    e();
    this.bs = (this.b + ".model.as");
    this.bt = "uE";
  }
  
  private void g()
  {
    this.m += ".z.n";
    this.k = "zW";
    this.aw = "hy";
    this.n += ".ak.n";
    this.i = "jl";
    this.l = "i";
    this.p = "jk";
    this.o += ".a.f";
    this.j = "aA";
    this.e = "fqQ";
    this.f = "kbM";
    this.B += ".a";
    this.q += "1";
    this.u += "a.b.b";
    this.r = "lr";
    this.s = "gcZ";
    this.v = "gcN";
    this.w = "ari";
    this.y = "z";
    this.A = "o";
    this.z = "arh";
    this.x = "arj";
    this.t = "art";
    this.C = "ak";
    this.D += "aqx";
    this.E = "iXe";
    this.G = "hw";
    this.H = "jD";
    this.I = "i";
    this.J = "to";
    this.K = "d";
    this.L += "cn.5.1";
    this.M += "c.c";
    this.N = "kfI";
    this.O = "kfF";
    this.P = "e";
    this.ao += "cn";
    this.Q = "auA";
    this.R = "tr";
    this.S = "j";
    this.T = "aEF";
    this.U = "tV";
    this.V = "avR";
    this.W = "ad";
    this.X = "gvw";
    this.Y = "iXh";
    this.Z = "iuh";
    this.aa = "ikW";
    this.ab = "atj";
    this.ac = "bh";
    this.ad = "sN";
    this.ae = "sP";
    this.af += "q";
    this.ag += "f";
    this.ai += "ah";
    this.ah += "h.f";
    this.aj += "h";
    this.ak += "d.ad";
    this.al += "d.am";
    this.am += "d.ai";
    this.an += "d.g";
    this.ap = "ag";
    this.aq = "atw";
    this.as = "tU";
    this.ar = "gjZ";
    this.at = "m";
    this.au = "ggb";
    this.av = "tV";
    this.ax = "ijp";
    this.ay = "asn";
    this.az = "iLi";
    this.aA = "grT";
    this.aC += "m";
    this.aD = "DF";
    this.aF += ".12";
    this.aG += ".2";
    this.aH = "d";
    this.aI = "qy";
    this.aJ = "koZ";
    this.aK = "kmJ";
    this.aM += ".2";
    this.aN += ".4";
    this.aO = "d";
    this.aP = "gsm";
    this.aQ = "aug";
    this.aR += "a.k";
    this.aS += ".a.a";
    this.aT = "kjc";
    this.aU = "kbQ";
    this.aV = "g";
    this.aX = "dBy";
    this.aY = "dDi";
    this.aZ = "gR";
    this.ba = "TP";
    this.bb = "bc";
    this.bc = "k";
    this.bd = "iyg";
    this.be = "d";
    this.bf = "c";
    this.bg = "asj";
    this.bh = "ixS";
    this.bi += "h";
    this.bj += "b.u";
    this.bm = "av";
    this.bn = "tn";
    this.bo = "rf";
    this.bq = "bz";
    this.bs += "as";
    this.bt = "uE";
    this.bv = (this.b + ".ac.g");
    this.bw += "f";
    this.bx += "f.d";
    this.by = "a";
    this.bB = (this.bz + ".4.1");
    this.bC = "ao";
    this.bD = "amb";
    this.bE = "fvl";
    this.bF = "fvk";
    this.bG = (this.bA + ".11.1");
    this.bH = (this.bA + ".11.2");
    this.bI += "k";
    this.bJ += "a.l";
    this.bK = "a";
    this.bL = "a";
    this.bM = "d";
    this.bN = "c";
    this.bS = "f";
    this.bO = "fvd";
    this.bP = "fva";
    this.bQ = "awv";
    this.bR = "avx";
    this.bT = (this.b + ".plugin.emoji.d");
    this.bU = "q";
    this.bV = "tn";
    this.bW = "rx";
  }
  
  private void h()
  {
    this.m += ".z.n";
    this.k = "zV";
    this.aw = "hC";
    this.n += ".ak.n";
    this.i = "ju";
    this.l = "j";
    this.p = "jt";
    this.o += ".a.g";
    this.j = "az";
    this.e = "fyu";
    this.f = "koY";
    this.B += ".a";
    this.q += "1";
    this.u += "a.b.b";
    this.r = "lg";
    this.s = "gkX";
    this.v = "gkL";
    this.w = "asW";
    this.y = "A";
    this.A = "n";
    this.z = "asV";
    this.x = "asX";
    this.t = "ath";
    this.C = "ak";
    this.D += "asd";
    this.E = "jjP";
    this.G = "hA";
    this.H = "jM";
    this.I = "i";
    this.J = "tm";
    this.K = "d";
    this.L += "cn.5.1";
    this.M += "c.c";
    this.N = "ksU";
    this.O = "ksR";
    this.P = "e";
    this.ao += "cn";
    this.Q = "awn";
    this.R = "tJ";
    this.S = "j";
    this.T = "aFe";
    this.U = "un";
    this.V = "awh";
    this.W = "ad";
    this.X = "gDy";
    this.Y = "jjS";
    this.Z = "iGq";
    this.aa = "iwV";
    this.ab = "auW";
    this.ac = "bf";
    this.ad = "tf";
    this.ae = "th";
    this.af += "q";
    this.ag += "f";
    this.ai += "ah";
    this.ah += "h.f";
    this.aj += "h";
    this.ak += "d.ad";
    this.al += "d.am";
    this.am += "d.ai";
    this.an += "d.g";
    this.ap = "ag";
    this.aq = "avj";
    this.as = "um";
    this.ar = "grY";
    this.at = "m";
    this.au = "goa";
    this.av = "un";
    this.ax = "dXh";
    this.ay = "asu";
    this.az = "iXN";
    this.aA = "gzW";
    this.aC += "m";
    this.aD = "DS";
    this.aF += ".12";
    this.aG += ".2";
    this.aH = "d";
    this.aI = "qN";
    this.aJ = "kCt";
    this.aK = "kzY";
    this.aM += ".2";
    this.aN += ".4";
    this.aO = "d";
    this.aP = "gAp";
    this.aQ = "avT";
    this.aR += "a.k";
    this.aS += ".a.a";
    this.aT = "kwq";
    this.aU = "eNH";
    this.aV = "g";
    this.aX = "dGd";
    this.aY = "dHN";
    this.aZ = "gU";
    this.ba = "UH";
    this.bb = "bc";
    this.bc = "k";
    this.bd = "iKu";
    this.be = "d";
    this.bf = "c";
    this.bg = "asq";
    this.bh = "iKg";
    this.bi += "h";
    this.bj += "b.u";
    this.bm = "au";
    this.bn = "tl";
    this.bo = "re";
    this.bq = "bB";
    this.bs += "at";
    this.bt = "tZ";
    this.bv += "g";
    this.bB = "";
    this.bT = (this.b + ".plugin.emoji.d");
    this.bU = "r";
    this.bV = "tl";
    this.bW = "rw";
  }
  
  private void i()
  {
    this.m += ".aa.n";
    this.k = "zZ";
    this.aw = "hF";
    this.n += ".am.n";
    this.i = "jx";
    this.l = "j";
    this.p = "jw";
    this.o += ".a.g";
    this.j = "aC";
    this.e = "fHr";
    this.f = "kHH";
    this.B += ".a";
    this.q += "1";
    this.u += "a.b.b";
    this.r = "lj";
    this.s = "gxR";
    this.v = "gxF";
    this.w = "avm";
    this.y = "A";
    this.A = "n";
    this.z = "avl";
    this.x = "avn";
    this.t = "avx";
    this.C = "al";
    this.D += "asz";
    this.E = "jBA";
    this.G = "hD";
    this.H = "jP";
    this.I = "i";
    this.J = "ts";
    this.K = "d";
    this.L += "cn.5.1";
    this.M += "c.c";
    this.N = "kLD";
    this.O = "kLA";
    this.P = "e";
    this.ao += "cn";
    this.Q = "azh";
    this.R = "ux";
    this.S = "m";
    this.T = "aFU";
    this.U = "vb";
    this.V = "awx";
    this.W = "ad";
    this.X = "gUK";
    this.Y = "jBD";
    this.Z = "iWV";
    this.aa = "iNz";
    this.ab = "axQ";
    this.ac = "bl";
    this.ad = "q";
    this.ae = "w";
    this.af += "q";
    this.ag += "f";
    this.ai += "ah";
    this.ah += "h.f";
    this.aj += "h";
    this.ak += "d.ad";
    this.al += "d.am";
    this.am += "d.ai";
    this.an += "d.g";
    this.ap = "ag";
    this.aq = "ayd";
    this.as = "va";
    this.ar = "gJp";
    this.at = "m";
    this.au = "gAU";
    this.av = "vb";
    this.ax = "edx";
    this.ay = "asI";
    this.az = "joC";
    this.aA = "gRo";
    this.aC += "m";
    this.aD = "Ec";
    this.aF += ".12";
    this.aG += ".2";
    this.aH = "d";
    this.aI = "rn";
    this.aJ = "kVi";
    this.aK = "kSN";
    this.aM += ".2";
    this.aN += ".4";
    this.aO = "d";
    this.aP = "gRH";
    this.aQ = "ayN";
    this.aR += "a.k";
    this.aS += ".a.a";
    this.aT = "kPc";
    this.aU = "eUF";
    this.aV = "h";
    this.aX = "dMp";
    this.aY = "dNZ";
    this.aZ = "gW";
    this.ba = "Vy";
    this.bb = "bd";
    this.bc = "k";
    this.bd = "jaZ";
    this.be = "d";
    this.bf = "c";
    this.bg = "asE";
    this.bh = "jaL";
    this.bi += "h";
    this.bj += "b.u";
    this.bm = "ax";
    this.bn = "tr";
    this.bo = "rf";
    this.bq = "bB";
    this.bs += "at";
    this.bt = "ue";
    this.bv += "h";
    this.bw += "g";
    this.bx += "g.d";
    this.by = "a";
    this.bB = (this.bz + ".4.1");
    this.bC = "aq";
    this.bD = "ape";
    this.bE = "fLM";
    this.bF = "fLL";
    this.bG = (this.bA + ".11.1");
    this.bH = (this.bA + ".11.2");
    this.bI += "l";
    this.bJ += "a.l";
    this.bK = "a";
    this.bL = "b";
    this.bM = "d";
    this.bN = "c";
    this.bS = "f";
    this.bO = "fLE";
    this.bP = "fLB";
    this.bQ = "axb";
    this.bR = "awd";
    this.bU = "r";
    this.bV = "tr";
    this.bW = "rx";
  }
  
  private void j()
  {
    this.m += ".ab.n";
    this.k = "Ao";
    this.aw = "hM";
    this.n += ".an.n";
    this.i = "jM";
    this.p = "jL";
    this.l = "j";
    this.o += ".a.g";
    this.j = "aC";
    this.e = "fNB";
    this.f = "kSE";
    this.B += ".a";
    this.q += "1";
    this.u += "a.b.b";
    this.r = "lj";
    this.s = "gEp";
    this.v = "gEd";
    this.w = "awp";
    this.y = "x";
    this.A = "n";
    this.z = "awo";
    this.x = "awq";
    this.t = "awA";
    this.C = "am";
    this.D += "atp";
    this.E = "jMu";
    this.G = "hK";
    this.H = "ke";
    this.I = "i";
    this.J = "tE";
    this.K = "d";
    this.L += "cp.5.1";
    this.M += "c.c";
    this.N = "kWy";
    this.O = "kWv";
    this.P = "beB";
    this.ao = "";
    this.Q = "aAl";
    this.R = "uK";
    this.S = "D";
    this.T = "aHW";
    this.U = "vo";
    this.V = "axC";
    this.W = "ad";
    this.X = "hbh";
    this.Y = "jMx";
    this.Z = "jhw";
    this.aa = "iXW";
    this.ab = "ayV";
    this.ac = "bp";
    this.ad = "c";
    this.ae = "i";
    this.af += "q";
    this.ag += "f";
    this.ai += "ah";
    this.ah += "h.f";
    this.aj += "h";
    this.ak += "d.ad";
    this.al += "d.am";
    this.am += "d.ai";
    this.an += "d.g";
    this.ap = "ag";
    this.aq = "azi";
    this.as = "vn";
    this.ar = "gPn";
    this.at = "m";
    this.au = "gHs";
    this.av = "vo";
    this.ax = "eiq";
    this.ay = "asP";
    this.az = "jzt";
    this.aA = "gXI";
    this.aC += "m";
    this.aD = "Ey";
    this.aF += ".15";
    this.aG += ".3";
    this.aH = "d";
    this.aI = "rq";
    this.aJ = "lgM";
    this.aK = "lel";
    this.aM += ".2";
    this.aN += ".4";
    this.aO = "d";
    this.aP = "gYc";
    this.aQ = "azR";
    this.aR += "a.k";
    this.aS += ".a.a";
    this.aT = "laF";
    this.aU = "faQ";
    this.aV = "i";
    this.aX = "dPX";
    this.aY = "dRH";
    this.aZ = "gQ";
    this.ba = "VS";
    this.bb = "bh";
    this.bc = "k";
    this.bd = "jlz";
    this.be = "d";
    this.bf = "c";
    this.bg = "asL";
    this.bh = "jlm";
    this.bi += "h";
    this.bj += "b.u";
    this.bm = "ax";
    this.bn = "tD";
    this.bo = "rn";
    this.bq = "bC";
    this.bs += "at";
    this.bt = "uq";
    this.bv += "h";
    this.bw += "g";
    this.bx += "g.d";
    this.by = "a";
    this.bB = (this.bz + ".4.1");
    this.bC = "aq";
    this.bD = "aqa";
    this.bE = "fRX";
    this.bF = "fRW";
    this.bG = (this.bA + ".11.1");
    this.bH = (this.bA + ".11.2");
    this.bI += "l";
    this.bJ += "a.m";
    this.bK = "a";
    this.bL = "b";
    this.bM = "d";
    this.bN = "c";
    this.bS = "f";
    this.bO = "fRP";
    this.bP = "fRM";
    this.bQ = "ayg";
    this.bR = "avg";
    this.bU = "r";
    this.bV = "tD";
    this.bW = "rF";
  }
  
  private void k()
  {
    j();
  }
  
  private void l()
  {
    this.m += ".ab.n";
    this.k = "Ao";
    this.aw = "hM";
    this.n += ".an.n";
    this.i = "jM";
    this.p = "jL";
    this.l = "j";
    this.o += ".a.g";
    this.j = "aC";
    this.e = "fOf";
    this.f = "kUq";
    this.B += ".a";
    this.q += "1";
    this.u += "a.b.b";
    this.r = "lj";
    this.s = "gET";
    this.v = "gEH";
    this.w = "awr";
    this.y = "x";
    this.A = "n";
    this.z = "awq";
    this.x = "aws";
    this.t = "awC";
    this.C = "am";
    this.D += "atq";
    this.E = "jNV";
    this.G = "hK";
    this.H = "ke";
    this.I = "i";
    this.J = "tE";
    this.K = "d";
    this.L += "cp.5.1";
    this.M += "c.c";
    this.N = "kYk";
    this.O = "kYh";
    this.P = "beW";
    this.ao = "";
    this.Q = "aAw";
    this.R = "uK";
    this.S = "D";
    this.T = "aIb";
    this.U = "vo";
    this.V = "axD";
    this.W = "ad";
    this.X = "hct";
    this.Y = "jNY";
    this.Z = "jiU";
    this.aa = "iZu";
    this.ab = "azg";
    this.ac = "bq";
    this.ad = "c";
    this.ae = "i";
    this.af += "q";
    this.ag += "f";
    this.ai += "ah";
    this.ah += "h.f";
    this.aj += "h";
    this.ak += "d.ad";
    this.al += "d.am";
    this.am += "d.ai";
    this.an += "d.g";
    this.ap = "ag";
    this.aq = "azt";
    this.as = "vn";
    this.ar = "gQt";
    this.at = "m";
    this.au = "gHV";
    this.av = "vo";
    this.ax = "eiD";
    this.ay = "asQ";
    this.az = "jAR";
    this.aA = "gYS";
    this.aC += "m";
    this.aD = "Ey";
    this.aF += ".15";
    this.aG += ".3";
    this.aH = "d";
    this.aI = "rp";
    this.aJ = "liy";
    this.aK = "lfy";
    this.aM += ".2";
    this.aN += ".4";
    this.aO = "d";
    this.aP = "gZm";
    this.aQ = "aAc";
    this.aR += "a.k";
    this.aS += ".a.a";
    this.aT = "lcr";
    this.aU = "fbn";
    this.aV = "i";
    this.aX = "dQi";
    this.aY = "dRS";
    this.aZ = "gQ";
    this.ba = "VS";
    this.bb = "bh";
    this.bc = "k";
    this.bd = "jmX";
    this.be = "d";
    this.bf = "c";
    this.bg = "asM";
    this.bh = "jmK";
    this.bi += "h";
    this.bj += "b.u";
    this.bm = "ax";
    this.bn = "tD";
    this.bo = "rn";
    this.bq = "bC";
    this.bs += "at";
    this.bt = "uq";
    this.bv += "h";
    this.bw += "g";
    this.bx += "g.d";
    this.by = "a";
    this.bB = (this.bz + ".4.1");
    this.bC = "aq";
    this.bD = "aqc";
    this.bE = "fSB";
    this.bF = "fSA";
    this.bG = (this.bA + ".11.1");
    this.bH = (this.bA + ".11.2");
    this.bI += "l";
    this.bJ += "a.m";
    this.bK = "a";
    this.bL = "b";
    this.bM = "d";
    this.bN = "c";
    this.bS = "f";
    this.bO = "fSt";
    this.bP = "fSq";
    this.bQ = "ayh";
    this.bR = "avh";
  }
  
  private void m()
  {
    this.m += ".ab.n";
    this.k = "zA";
    this.aw = "if";
    this.n += ".an.n";
    this.i = "kc";
    this.p = "kb";
    this.l = "l";
    this.o += ".a.g";
    this.j = "aG";
    this.e = "fGR";
    this.f = "kMB";
    this.B += ".a";
    this.q += "1";
    this.u += "a.b.b";
    this.r = "jQ";
    this.s = "gtw";
    this.v = "gtk";
    this.w = "avt";
    this.y = "v";
    this.A = "o";
    this.z = "avs";
    this.x = "avu";
    this.t = "avE";
    this.C = "ak";
    this.D += "atl";
    this.E = "jFi";
    this.G = "ic";
    this.H = "ku";
    this.I = "i";
    this.J = "sQ";
    this.K = "d";
    this.L += "cq.5.1";
    this.M += "c.c";
    this.N = "kQv";
    this.O = "kQs";
    this.P = "bey";
    this.ao = "";
    this.Q = "azq";
    this.R = "uJ";
    this.S = "D";
    this.T = "auM";
    this.U = "vm";
    this.V = "aku";
    this.W = "ad";
    this.X = "gSv";
    this.Y = "jFl";
    this.Z = "jau";
    this.aa = "iQO";
    this.ab = "axY";
    this.ac = "bq";
    this.ad = "c";
    this.ae = "i";
    this.af += "q";
    this.ag += "f";
    this.ai += "ah";
    this.ah += "h.f";
    this.aj += "i";
    this.ak += "d.ad";
    this.al += "d.am";
    this.am += "d.ai";
    this.an += "d.g";
    this.ap = "ag";
    this.aq = "ayl";
    this.as = "vl";
    this.ar = "auE";
    this.at = "m";
    this.au = "ahL";
    this.av = "vm";
    this.ax = "ebm";
    this.ay = "aft";
    this.az = "jsw";
    this.aA = "gOU";
    this.aC += "m";
    this.aD = "DK";
    this.aF += ".15";
    this.aG += ".3";
    this.aH = "d";
    this.aI = "rR";
    this.aJ = "laH";
    this.aK = "kYg";
    this.aM += ".2";
    this.aN += ".4";
    this.aO = "d";
    this.aP = "gPo";
    this.aQ = "ayW";
    this.aR += "a.k";
    this.aS += ".a.a";
    this.aT = "kUC";
    this.aU = "eTY";
    this.aV = "i";
    this.aX = "dIm";
    this.aY = "dJW";
    this.aZ = "hu";
    this.ba = "VC";
    this.bb = "bh";
    this.bc = "l";
    this.bd = "jez";
    this.be = "d";
    this.bf = "c";
    this.bg = "afp";
    this.bh = "jem";
    this.bi += "h";
    this.bj += "b.v";
    this.bm = "aB";
    this.bn = "sP";
    this.bo = "qC";
    this.bq = "bh";
    this.bs += "at";
    this.bt = "tB";
    this.bv += "h";
    this.bw += "g";
    this.bx += "g.d";
    this.by = "a";
    this.bB = (this.bz + ".4.1");
    this.bC = "av";
    this.bD = "aqf";
    this.bE = "fLn";
    this.bF = "fLm";
    this.bG = (this.bA + ".11.1");
    this.bH = (this.bA + ".11.2");
    this.bI += "l";
    this.bJ += "a.m";
    this.bK = "a";
    this.bL = "b";
    this.bM = "d";
    this.bN = "c";
    this.bS = "f";
    this.bO = "fLf";
    this.bP = "fLc";
    this.bQ = "akY";
    this.bR = "ahK";
  }
  
  private void n()
  {
    this.m = this.b;/** Modify By Gele **///包名
    this.k = "";
    this.aw = "";
    this.d = (this.b + ".ui.chatting.ChattingUI");
    this.c = (this.b + ".ui.LauncherUI");
    this.F = (this.b + ".ui.transmit.SelectConversationUI");
    this.aW = (this.b + ".plugin.favorite.ui.FavoriteIndexUI");
    this.l = "";
    this.n = this.b;
    this.i = "";
    this.p = "";
    this.h = (this.b + ".plugin.sns.ui.SightUploadUI");
    this.g = (this.b + ".plugin.sns.ui.SnsUploadUI");
    this.e = "";
    this.f = "";
    this.B = this.d;
    this.o = this.b;
    this.j = "";
    this.q = (this.b + ".plugin.sight.encode.ui.SightCameraView.");
    this.u = (this.b + ".plugin.sight.encode.");
    this.r = "";
    this.s = "";
    this.v = "";
    this.w = "";
    this.y = "";
    this.A = "";
    this.z = "";
    this.x = "";
    this.t = "";
    this.C = "";
    this.D = (this.b + ".protocal.b.");
    this.E = "";
    this.G = "";
    this.H = "";
    this.I = "";
    this.J = "";
    this.K = "";
    this.L = (this.b + ".ui.chatting.");
    this.M = (this.b + ".plugin.sns.ui.");
    this.N = "";
    this.O = "";
    this.P = "";
    this.Q = "";
    this.R = "";
    this.S = "";
    this.T = "";
    this.U = "";
    this.V = "";
    this.W = "";
    this.X = "";
    this.Y = "";
    this.Z = "";
    this.aa = "";
    this.ab = "";
    this.ac = "";
    this.ad = "";
    this.ae = "";
    this.af = (this.b + ".modelvoice.");
    this.ag = this.af;
    this.ai = (this.b + ".model.");
    this.ah = (this.b + ".plugin.sns.");
    this.aj = (this.b + ".plugin.sns.data.");
    this.ak = (this.b + ".plugin.sns.");
    this.al = (this.b + ".plugin.sns.");
    this.am = (this.b + ".plugin.sns.");
    this.an = (this.b + ".plugin.sns.");
    this.ao = (this.b + ".ui.chatting.");
    this.aB = (this.b + ".ui.transmit.MsgRetransmitUI");
    this.aE = (this.b + ".ui.chatting.gal.plugin.snslery.ImageGalleryUI");
    this.aL = (this.b + ".plugin.sns.ui.FlipView");
    this.bp = (this.b + ".plugin.sns.ui.SnsTimeLineUI");
    this.br = (this.b + ".plugin.sns.ui.SnsCommentDetailUI");
    this.bu = (this.b + ".plugin.sns.ui.SnsGalleryUI");
    this.bz = (this.b + ".plugin.record.ui.RecordMsgImageUI");
    this.bA = (this.b + ".plugin.record.ui.RecordMsgFileUI");
    this.bX = (this.a + ".kingkong.database.SQLiteDatabase");
    this.ap = "";
    this.aq = "";
    this.as = "";
    this.ar = "";
    this.at = "";
    this.au = "";
    this.ax = "";
    this.ay = "";
    this.az = "";
    this.aA = "";
    this.aC = (this.b + ".modelvoice.");
    this.aD = "";
    this.aF = this.aE;
    this.aG = this.aE;
    this.aH = "";
    this.aI = "";
    this.aJ = "";
    this.aK = "";
    this.aM = this.aL;
    this.aN = this.aL;
    this.aO = "";
    this.aP = "";
    this.aR = (this.b + ".plugin.chatroom.");
    this.aS = this.d;
    this.aT = "";
    this.aU = "";
    this.aV = "";
    this.aX = "";
    this.aY = "";
    this.aZ = "";
    this.ba = "";
    this.bb = "";
    this.bc = "";
    this.bd = "";
    this.be = "";
    this.bf = "";
    this.bg = "";
    this.bh = "";
    this.bi = (this.b + ".plugin.favorite.");
    this.bj = (this.b + ".plugin.favorite.");
    this.bk = 0;
    this.bl = (this.b + ".modelsfs.FileOp");
    this.bm = "";
    this.bs = (this.b + ".model.");
    this.bv = (this.b + ".modelmulti.");
    this.bw = (this.b + ".ui.base.");
    this.bx = (this.b + ".ui.base.");
    this.bI = (this.b + ".ui.base.");
    this.bJ = (this.b + ".plugin.record.");
    this.bT = (this.b + ".plugin.emoji.model.EmojiLogic");
  }
}



/* Location:           C:\Users\John\Desktop\APKDecompile\projects\fkzhang.wechatforwarder_13\ProjectSrc\smali\

 * Qualified Name:     com.fkzhang.wechatforwarder.f

 * JD-Core Version:    0.7.0.1

 */